# Generated by Django 4.2.5 on 2023-10-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='campers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_contributor', models.BooleanField(default=True)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
