# Generated by Django 4.2.5 on 2023-10-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_campers_is_contributor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='campers',
        ),
    ]
