# Generated by Django 4.2.5 on 2023-10-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsite',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.3, max_digits=2),
            preserve_default=False,
        ),
    ]
