# Generated by Django 4.2.5 on 2023-10-30 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_campsite_num_of_ratings_alter_campsite_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campsite',
            old_name='rating',
            new_name='total_rating',
        ),
        migrations.AddField(
            model_name='campsite',
            name='site_address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='campsite',
            name='site_description',
            field=models.CharField(max_length=10000),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('site_description', models.CharField(max_length=10000)),
                ('rating', models.IntegerField()),
                ('allows_campfires', models.BooleanField(default=None)),
                ('potable_water', models.BooleanField(default=None)),
                ('outhouse', models.BooleanField(default=None)),
                ('neaby_trees', models.BooleanField(default=None)),
                ('trail_access', models.BooleanField(default=None)),
                ('has_bugs', models.BooleanField(default=None)),
                ('equipment_access', models.BooleanField(default=None)),
                ('privacy_rating', models.IntegerField(default=None)),
                ('campsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.campsite')),
            ],
        ),
    ]
