# Generated by Django 4.2.5 on 2023-10-30 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_rating_campsite_total_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campsite',
            name='site_description',
        ),
    ]
