# Generated by Django 4.2.5 on 2023-10-31 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_campsite_site_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='neaby_trees',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
        migrations.AddField(
            model_name='review',
            name='nearby_trees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='user_email',
            field=models.CharField(default='johndoe@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='allows_campfires',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='campsite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.campsite'),
        ),
        migrations.AlterField(
            model_name='review',
            name='equipment_access',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='has_bugs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='outhouse',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='potable_water',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='trail_access',
            field=models.IntegerField(default=0),
        ),
    ]
