# Generated by Django 4.2.5 on 2023-10-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_review_neaby_trees_remove_review_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campsite',
            name='site_address',
            field=models.CharField(max_length=100),
        ),
    ]
