# Generated by Django 4.2.6 on 2023-11-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/admin/images/defaultPFP.png', upload_to='profile_pics/'),
        ),
    ]
