# Generated by Django 4.2.5 on 2023-11-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_review_approved_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='privacy_rating',
            field=models.IntegerField(default=0),
        ),
    ]
