# Generated by Django 4.2.6 on 2023-11-14 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='review',
        ),
        migrations.AddField(
            model_name='favorites',
            name='campsite',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='users.campsite'),
        ),
    ]
