# Generated by Django 4.2.6 on 2023-11-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/defaultPFP.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
