# Generated by Django 4.2.6 on 2023-11-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='defaultPFP.png', upload_to='profile_pictures/'),
        ),
    ]
