# Generated by Django 4.2.6 on 2023-12-03 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_favorites_review_favorites_campsite'),
        ('users', '0024_alter_profile_profile_picture'),
    ]

    operations = [
    ]
